# Generated by Django 5.2.6 on 2026-01-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="logo",
            field=models.CharField(max_length=255),
        ),
    ]
