# Generated by Django 5.2.6 on 2026-01-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_store_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="logo",
            field=models.CharField(blank=True, default="My Logo", max_length=255),
        ),
    ]
