# Generated by Django 5.2.6 on 2026-01-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_store_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="logo",
            field=models.CharField(max_length=255),
        ),
    ]
