# Generated by Django 5.2.6 on 2026-01-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_store_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Product_image",
            new_name="product_image",
        ),
        migrations.RemoveField(
            model_name="store",
            name="logo",
        ),
    ]
